<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'RH\\Model\\PlayItem' => 'RH/Model/PlayItem.php',
  'RH\\Model\\PlayItemPeer' => 'RH/Model/PlayItemPeer.php',
  'RH\\Model\\PlayItemQuery' => 'RH/Model/PlayItemQuery.php',
  'RH\\Model\\Song' => 'RH/Model/Song.php',
  'RH\\Model\\SongPeer' => 'RH/Model/SongPeer.php',
  'RH\\Model\\SongQuery' => 'RH/Model/SongQuery.php',
  'RH\\Model\\map\\PlayItemTableMap' => 'RH/Model/map/PlayItemTableMap.php',
  'RH\\Model\\map\\SongTableMap' => 'RH/Model/map/SongTableMap.php',
  'RH\\Model\\om\\BasePlayItem' => 'RH/Model/om/BasePlayItem.php',
  'RH\\Model\\om\\BasePlayItemPeer' => 'RH/Model/om/BasePlayItemPeer.php',
  'RH\\Model\\om\\BasePlayItemQuery' => 'RH/Model/om/BasePlayItemQuery.php',
  'RH\\Model\\om\\BaseSong' => 'RH/Model/om/BaseSong.php',
  'RH\\Model\\om\\BaseSongPeer' => 'RH/Model/om/BaseSongPeer.php',
  'RH\\Model\\om\\BaseSongQuery' => 'RH/Model/om/BaseSongQuery.php',
);