<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /Users/mdarse/Projects/advanced-php/radio-hipster/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'radio-hipster' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:unix=/tmp/mysql.sock;dbname=radio-hipster',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'radio-hipster',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-radio-hipster-conf.php');
return $conf;